// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD74WlX6tVXL6opjjQky8ZWnKfg9Shm2eY',
    appId: '1:680930418161:android:3af728659c465491673850',
    messagingSenderId: '680930418161',
    projectId: 'astro-darshan-a4ac5',
    databaseURL: 'https://astro-darshan-a4ac5-default-rtdb.firebaseio.com',
    storageBucket: 'astro-darshan-a4ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKL3s9HKi6vP9_k_W3Ky0UV2qE4Ae-VyU',
    appId: '1:680930418161:ios:c667149be6daad4d673850',
    messagingSenderId: '680930418161',
    projectId: 'astro-darshan-a4ac5',
    databaseURL: 'https://astro-darshan-a4ac5-default-rtdb.firebaseio.com',
    storageBucket: 'astro-darshan-a4ac5.appspot.com',
    iosBundleId: 'com.astrodarshan.partner',
  );


}

